apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
        -o kubemanifests.yaml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: language-core
    name: language-core
  spec:
    ports:
    - name: "8189"
      port: 8189
      targetPort: 8189
    selector:
      io.kompose.service: language-core
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
        -o kubemanifests.yaml
      kompose.version: 1.21.0 (992df58d8)
    creationTimestamp: null
    labels:
      io.kompose.service: language-core
    name: language-core
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: language-core
    strategy: {}
    template:
      metadata:
        annotations:
          kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
            -o kubemanifests.yaml
          kompose.version: 1.21.0 (992df58d8)
        creationTimestamp: null
        labels:
          io.kompose.service: language-core
      spec:
        containers:
        - args:
          - sh
          - -c
          - |-
            python manage.py migrate &
                   python manage.py runserver 0.0.0.0:8189 --noreload
          image: dltk-language-core
          imagePullPolicy: ""
          name: dltk-language-core
          ports:
          - containerPort: 8189
          resources: {}
        restartPolicy: Always
        serviceAccountName: ""
        volumes: null
  status: {}
kind: List
metadata: {}

